name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        echo "Dependencies installed"


    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker pull owasp/zap2docker-stable
        docker run -v $(pwd):/zap/wrk/:rw \
          owasp/zap2docker-stable zap-baseline.py \
          -t https://ccse-1-u5534801.onrender.com \
          -r zap-report.html || true
